name: Docker CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Code Pull Karo
      uses: actions/checkout@v4

    - name: Docker Image Build Karo
      run: docker build -t my-demo-app .

    - name: Docker Container Run Karo
      run: docker run my-demo-app
